cronc2x should be more silent

diff --git a/bin/cronc2x b/bin/cronc2x
--- a/bin/cronc2x
+++ b/bin/cronc2x
@@ -11,11 +11,11 @@ pgrep=/usr/bin/pgrep
 csync2=/opt/local/sbin/csync2
 
 if ! [ -e ${MUSTEXIST} ]; then
-	echo "ERROR: Folder does not exist: ${MUSTEXIST}" >&2
+#	echo "ERROR: Folder does not exist: ${MUSTEXIST}" >&2
 	exit 1
 fi
 if [ -e /etc/csync2.bootlock ]; then
-	echo "ERROR: $0 will not run if /etc/csync2.bootlock exists" >&2
+#	echo "ERROR: $0 will not run if /etc/csync2.bootlock exists" >&2
 	exit 1
 fi
 
@@ -24,12 +24,12 @@ REMOTE=$( $netstat -an -f inet | $grep '\.30865.* ESTABLISHED' | $awk '{print $4
 LOCAL=$( $pgrep -lf csync2 | $grep '\-x' )
 
 if [ "x" != "x${REMOTE}" ]; then
-	echo "ERROR: csync2 client already connected from remote" >&2
-	echo "${REMOTE}" >&2
+#	echo "ERROR: csync2 client already connected from remote" >&2
+#	echo "${REMOTE}" >&2
 	exit 1
 elif [ "x" != "x${LOCAL}" ]; then
-	echo "ERROR: csync2 client already running from local" >&2
-	echo "${LOCAL}" >&2
+#	echo "ERROR: csync2 client already running from local" >&2
+#	echo "${LOCAL}" >&2
 	exit 1
 else
 	$csync2 ${DATABASE} ${PCNAME} -x -v "$@" || echo $?
